spring:
  datasource:
    name: security
    url: jdbc:mysql://localhost:3306/spring-security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root

    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  redis:
    redisson:
      config: |
        singleServerConfig:
          password: 12@3qwR
          address: "redis://127.0.0.1:6379"
          database: 0
        threads: 0
        nettyThreads: 0
        codec: !<org.redisson.client.codec.StringCodec> {}
        transportMode: "NIO"

mybatis-plus:
  mapper-locations: classpath:com/bruce/security/sqlmap/auto/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  defaultExcludeUrls: [ "/security/login", "/security/secretKey", "/security/showResScript","/security/showResTree", "/security/images/captcha", "/security/redirect", "/error" ]
  swaggerUrls: [ "/doc.html", "/v2/api-docs", "/v2/api-docs-ext","/swagger-resources", "/webjars/**" ]
  token:
    type: REDIS
    expire: 172800000
    name: securitytoken
  captcha:
    enable: Y
    expire: 120
    length: 16
    name: rid
  retry:
    expire: 7200

